# Translations template for nova_powervm.
# Copyright (C) 2016 IBM Corp.
# This file is distributed under the same license as the nova_powervm
# project.
# Automatically generated, 2016.
#
msgid ""
msgstr ""
"Project-Id-Version: nova_powervm 3.0.0.0rc2.dev10\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2016-10-07 02:04-0400\n"
"PO-Revision-Date: 2016-10-07 02:04-0400\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.3.4\n"

#: nova_powervm/virt/powervm/driver.py:1548
msgid "Live migration timed out. Aborting migration"
msgstr "ライブ・マイグレーションがタイムアウトになりました。"
"マイグレーションを中止します"

#: nova_powervm/virt/powervm/live_migration.py:331
msgid "Live migration failed."
msgstr "ライブ・マイグレーションが失敗しました。"

#: nova_powervm/virt/powervm/live_migration.py:385
#, python-format
msgid "Migration recover failed with error: %s"
msgstr "マイグレーション・リカバリーが失敗しました。エラー: %s"

#: nova_powervm/virt/powervm/live_migration.py:413
msgid ""
"Abort of live migration has failed. This is non-blocking. Exception is "
"logged below."
msgstr ""
"ライブ・マイグレーションの中止に失敗しました。これは非ブロッキングです。"
"例外は下に記録されています。"

#: nova_powervm/virt/powervm/vif.py:106
#, python-format
msgid "Custom VIF event push failed.  %s"
msgstr "カスタム VIF イベント・プッシュが失敗しました。%s"

#: nova_powervm/virt/powervm/vif.py:316
#, python-format
msgid "Unable to unplug VIF with mac %(mac)s for instance %(inst)s."
msgstr "インスタンス %(inst)s の VIF (mac %(mac)s) のアンプラグすることが"
"できません。"

#: nova_powervm/virt/powervm/vm.py:646
#, python-format
msgid "Virtual machine delete failed: LPARID=%s"
msgstr "仮想マシン削除に失敗しました: LPARID=%s"

#: nova_powervm/virt/powervm/disk/localdisk.py:258
#, python-format
msgid "Disk %s not found during resize."
msgstr "サイズ変更中にディスク %s が見つかりませんでした。"

#: nova_powervm/virt/powervm/disk/ssp.py:331
#, python-format
msgid "Error checking for shared storage. exception=%s"
msgstr "共用ストレージのエラーを検査中です。例外=%s"

#: nova_powervm/virt/powervm/nvram/manager.py:109
#: nova_powervm/virt/powervm/nvram/manager.py:178
#, python-format
msgid "Could not update NVRAM: %s"
msgstr "NVRAM を更新できませんでした: %s"

#: nova_powervm/virt/powervm/tasks/network.py:66
#, python-format
msgid ""
"Unable to remove VIFs from instance %(inst)s because the system is not in a "
"correct state.  The reason reported by the system is: %(reason)s"
msgstr ""
"システムの状態が正しくないため、インスタンス %(inst)s から VIF を"
"削除できません。システムから報告された理由: %(reason)s"

#: nova_powervm/virt/powervm/tasks/network.py:154
#, python-format
msgid ""
"Unable to create VIF(s) for instance %(sys)s.  The VM was in a state where "
"VIF plugging is not acceptable.  The reason from the system is: %(reason)s"
msgstr ""
"インスタンス %(sys)s について VIF を作成できません。VM は、VIF プラグ接続が"
"受け入れ不可である状態にありました。システムから報告された理由: %(reason)s"

#: nova_powervm/virt/powervm/tasks/network.py:207
#, python-format
msgid "Error waiting for VIF to be created for instance %(sys)s"
msgstr "インスタンス %(sys)s の VIF 作成を待機中にエラーが発生しました"

#: nova_powervm/virt/powervm/tasks/network.py:221
#, python-format
msgid "VIF Plug failure for callback on event %(event)s for instance %(uuid)s"
msgstr "インスタンス %(uuid)s のイベント %(event)s でのコールバックの "
"VIF プラグ障害"

#: nova_powervm/virt/powervm/tasks/vm.py:283
#, python-format
msgid "Unable to store NVRAM for instance %(name)s. Exception: %(reason)s"
msgstr "インスタンス %(name)s の NVRAM を格納できません。例外: %(reason)s"

#: nova_powervm/virt/powervm/tasks/vm.py:313
#, python-format
msgid "Unable to delete NVRAM for instance %(name)s. Exception: %(reason)s"
msgstr "インスタンス %(name)s の NVRAM を削除できません。例外: %(reason)s"

#: nova_powervm/virt/powervm/volume/iscsi.py:221
#: nova_powervm/virt/powervm/volume/vscsi.py:334
#, python-format
msgid "Cannot detach volumes from virtual machine: %s"
msgstr "ボリュームを仮想マシンから切り離すことができません: %s"

#: nova_powervm/virt/powervm/volume/iscsi.py:223
#: nova_powervm/virt/powervm/volume/vscsi.py:336
#, python-format
msgid "Error: %s"
msgstr "エラー: %s"

#: nova_powervm/virt/powervm/volume/npiv.py:515
#, python-format
msgid ""
"Mappings were not able to find a proper VIOS. The port mappings were %s."
msgstr ""
"正しい VIOS をマッピングで検出できませんでした。ポート・マッピングは %s でした。"

# ENGL1SH_VERS10N 37135_5 DO NOT REMOVE OR CHANGE THIS LINE
# T9N_SRC_ID 44
# T9N_SH1P_STR1NG PV132AAP001 2
